### ISSUE TITLE
bookmark list not scrollable

### ISSUE THREAD

**Issue by anatolytkach** [UziTech/ContextMenuBookmarks#1]
Hi UziTech,
Thanks a lot for a great chrome extension. It works perfectly om my Win10 PC. 
However, on my other PC (Win8, latest Chrome version installed) the bookmarks list (I have a long one) is not scroll-able by the mouse wheel, and it is not even showing the down arrow at the bottom edge, where it is ending by the Windows taskbar.
Please, advise.
Thanks, Anatoly

**Comment by UziTech** [comment]
Are you talking about the context menu not being able to scroll? Unfortunately I don't have control over that.

This extension only adds bookmarks to the context menu. It can't control how the context menu renders them.

**Comment by UziTech** [comment]
I can only suggest maybe breaking your bookmarks into folders.
